### ISSUE TITLE
Make This Repo Private?

### ISSUE THREAD

**Issue by metaskills** [customink/.github#9]
Is it possible and/or what is the right way?

**Comment by ShaunaGordon** [comment]
Do you know if doing so will break any automations or anything? Or do you know where/how we can verify that before doing so?

**Comment by metaskills** [comment]
No, but I think we need to do it anyway and address the fallout, if any. I can help with that next week.

**Comment by metaskills** [comment]
Scratch that, seems this repo has to be public and the more logical .github-private (which we have) still does not support this. Details here:

https://github.com/orgs/community/discussions/42499
